version: '3.9'

services:
  db:
    image: postgres:14.3
    container_name: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    volumes:
      - ./postgres:/var/lib/postgresql/data
